### ISSUE TITLE
Different code generation between CLI and eclipse plugin

### ISSUE THREAD

**Issue by Cempl** [GENIVI/capicxx-core-tools#11]
I have code generator Common API C++ Core Generator 3.1.12.v201706201437. 
After code generation using CLI, these files have been created:
![cli](https://user-images.githubusercontent.com/20451730/38016870-124037d6-3279-11e8-8742-43c2ad43a764.png)
and it looks good. However, when I use eclipse plugin for code-generation, the generated files are different and some of them are missing comparing to CLI:
![eclipse](https://user-images.githubusercontent.com/20451730/38016909-375d0cce-3279-11e8-951a-9eb5500a44a1.png)
Eclipse Version: Oxygen.3 Release (4.7.3)
Look on cmake output.

Versions for CLI and Eclipse plugin are exactly the same.

**Comment by Cempl** [comment]
Problem resolved. Had need mark all checkboxes in project properties.
![settings](https://user-images.githubusercontent.com/20451730/38080966-873e0112-334b-11e8-87d6-514fdb7c0364.png)

**Comment by gunnarx** [comment]
Thanks for documenting your experience.
