### ISSUE TITLE
"No matching function.." build error in generated code for E02Attributes example

### ISSUE THREAD

**Issue by kbailey1128** [GENIVI/capicxx-core-tools#12]
I get the following error when trying to build the E02Attributes example: no matching function for call to ‘CommonAPI::SomeIP::GetAttributeStubDispatcher<v1::commonapi::examples::E02AttributesStub, int, CommonAPI::SomeIP::IntegerDeployment<int> >::GetAttributeStubDispatcher(void (v1::commonapi::examples::E02AttributesStub::*)(bool), const int32_t& (v1::commonapi::examples::E02AttributesStub::*)(std::shared_ptr<CommonAPI::ClientId>), bool)’

**Comment by mcirsta** [comment]
I've also gotten this error in one of my project but still have not found a solution. I've updated to the latest stable releases from both generator and libraries and yet I still get this error.

**Comment by lutzbichler** [comment]
This looks as if the versions of runtime and tools do not match. Please check with the latest version.
