### ISSUE TITLE
build error on ubuntu 16.04

### ISSUE THREAD

**Issue by 007herelsp** [GENIVI/capicxx-core-tools#14]
## log
```
[INFO] --- xtend-maven-plugin:2.7.3:compile (default) @ org.genivi.commonapi.releng ---
[WARNING] Error injecting: org.eclipse.xtend.maven.XtendCompile
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, com.google.inject.internal.util.$ComputationException: com.google.inject.internal.util.$ComputationException: com.google.inject.internal.util.$ComputationException: com.google.inject.internal.util.$ComputationException: com.google.inject.internal.util.$ComputationException: com.google.inject.internal.util.$ComputationException: java.lang.SecurityException: class "org.eclipse.core.runtime.OperationCanceledException"'s signer information does not match signer information of other classes in the same package
  at org.eclipse.xtend.maven.XtendCompile.<init>(XtendCompile.java:28)
  while locating org.eclipse.xtend.maven.XtendCompile


[ERROR] Failed to execute goal org.eclipse.xtend:xtend-maven-plugin:2.7.3:compile (default) on project org.genivi.commonapi.releng: Execution default of goal org.eclipse.xtend:xtend-maven-plugin:2.7.3:compile failed: Unable to load the mojo 'compile' (or one of its required components) from the plugin 'org.eclipse.xtend:xtend-maven-plugin:2.7.3': com.google.inject.ProvisionException: Unable to provision, see the following errors:
[ERROR]
[ERROR] 1) Error injecting constructor, com.google.inject.internal.util.$ComputationException: com.google.inject.internal.util.$ComputationException: com.google.inject.internal.util.$ComputationException: com.google.inject.internal.util.$ComputationException: com.google.inject.internal.util.$ComputationException: com.google.inject.internal.util.$ComputationException: java.lang.SecurityException: class "org.eclipse.core.runtime.OperationCanceledException"'s signer information does not match signer information of other classes in the same package
[ERROR] at org.eclipse.xtend.maven.XtendCompile.<init>(XtendCompile.java:28)
[ERROR] while locating org.eclipse.xtend.maven.XtendCompile
[ERROR] at ClassRealm[plugin>org.eclipse.xtend:xtend-maven-plugin:2.7.3, parent: sun.misc.Launcher$AppClassLoader@1b6d3586] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
[ERROR] while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=org.eclipse.xtend:xtend-maven-plugin:2.7.3:compile)
[ERROR]
[ERROR] 1 error
[ERROR] role: org.apache.maven.plugin.Mojo
[ERROR] roleHint: org.eclipse.xtend:xtend-maven-plugin:2.7.3:compile
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
```

**Comment by razvan-ciochina** [comment]
I've had the same error but, after a period I'm not proud of, I've realized that I was cd-ing to the wrong folder.
There are two folders ending in releng. The correct one is indeed specified correctly in the Readme: org.genivi.commonapi.core.releng (mind the "core" part).

**Comment by CalebProvost** [comment]
Same problem here, however, @razvan-ciochina 's fix isn't working for me...

**Comment by AzadaShams** [comment]
Hello,

I have been having the same problem on Ubuntu 20.04 (64 bit System) with Eclipse version 4.16. I changed the Xtend version to 2.22.0 and then Tycho version to 1.7.0, but I got the following erro:

Failed to execute goal org.eclipse.tycho:tycho-p2-director-plugin:1.5.0:materialize-products (materialize-products) on project org.genivi.commonapi.core.cli.product: Installation of product org.genivi.commonapi.core.cli.product for environment win32/win32/x86 failed: Call to p2 director application failed with exit code 13. Program arguments were: [-metadataRepository, file:/root/capicxx-core-tools/org.genivi.commonapi.core.cli.product/target/,file:/root/capicxx-core-tools/org.genivi.commonapi.core.cli.product/target/targetPlatformRepository/, -artifactRepository, file:/root/capicxx-core-tools/org.genivi.commonapi.core.cli.product/target/,file:/resolution-context-artifacts@%252Froot%252Fcapicxx-core-tools%252Forg.genivi.commonapi.core.cli.product,file:/root/capicxx-core-tools/org.genivi.commonapi.console/target/,file:/root/capicxx-core-tools/org.genivi.commonapi.console.feature/target/,file:/root/capicxx-core-tools/org.genivi.commonapi.console.franca.feature/target/,file:/root/capicxx-core-tools/org.genivi.commonapi.core/target/,file:/root/capicxx-core-tools/org.genivi.commonapi.core.cli/target/,file:/root/capicxx-core-tools/org.genivi.commonapi.core.cli.feature/target/,file:/root/capicxx-core-tools/org.genivi.commonapi.core.cli.product/target/,file:/root/.m2/repository/, -installIU, org.genivi.commonapi.core.cli.product, -destination, /root/capicxx-core-tools/org.genivi.commonapi.core.cli.product/target/products/org.genivi.commonapi.core.cli.product/win32/win32/x86, -profile, DefaultProfile, -profileProperties, org.eclipse.update.install.features=true, -roaming, -p2.os, win32, -p2.ws, win32, -p2.arch, x86]. -> [Help 1]
Could this error be related to 64 bit eclipse and Ubuntu version? Are these generators available only for 32 bit Ubuntu and Eclipse ? 
Also, I tried installing CommonApI generators through the given update sites in the user guide. However, the .fidl file was not transformed to C++ code? Please let me know what could have gone wrong!

**Comment by lutzbichler** [comment]
Ubuntu 20.04 / x64 is fine. The xtend version was updated for v3.2.0
