### ISSUE TITLE
Exec format error on Arm64 machine

### ISSUE THREAD

**Issue by emrebayrm** [GENIVI/capicxx-core-tools#19]
I compiled on arm64 machine using instructions in readme file. By the way, the device is NVidia Jetson Xavier. But when I try to generate a code from an example which is the helloworld project. But gives this error
./commonapi-generator-linux-x86_64 ../../../../../fidl/E01HelloWorld.fidl
-bash: ./commonapi-generator-linux-x86_64: cannot execute binary file: Exec format error
I try with with "commonapi-generator-linux-x86" it gives me same error but it is expected, anyway.

I suppose that the error is related to architecture but I compiled on the same devices and there is no reason to happen in my assumption.

Is there any support for Arm64 or is there any restriction to do that?
Next question, Is there any difference to execute the generator in a different platform? I mean is there any difference in the generated code according to a platform that it runs on? Then I can copy the generated codes to my arm64 platform and compile in it. 

I guess, there is not support for ARM.
Thanks in advance.

**Comment by lutzbichler** [comment]
We currently do not support ARM.

**Comment by jadhsha01** [comment]
Is ARM64 still not supported?

**Comment by TatianaLeal1125** [comment]
Is arm64 supported?
