### ISSUE TITLE
Negative enumerators are changed to 0.

### ISSUE THREAD

**Issue by lmzf318** [GENIVI/capicxx-core-tools#22]
Because of [this line of code](https://github.com/GENIVI/capicxx-core-tools/blob/master/org.genivi.commonapi.core/src/org/genivi/commonapi/core/generator/FrancaGeneratorExtensions.xtend#L1852) in `FrancaGeneratorExtensions`,  negative values are set to null. And thus following code translate them to '0'.

A potential simple fix may return the actual value instead of null:
```
    def static String getEnumeratorValue(FExpression expression)
    {
        return switch (expression)
        {
            FIntegerConstant: expression.^val.toString
            FStringConstant: expression.^val
            FQualifiedElementRef: expression.element.constantValue
            default: String.valueOf(ExpressionEvaluator::evaluateInteger(expression))
        }
    }
```
(A more generic solution can evaluate boolean, integer, and string by calling `ExpressionEvaluator`. Or make `ExpressionEvaluator.evaluate` public in franca and build with core_rools to call it here)

**Comment by lutzbichler** [comment]
Fixed with v3.2.0.
