### ISSUE TITLE
Facing communication issue in SOME/IP between FRANCA  Common API C++ Server and Python client 

### ISSUE THREAD

**Issue by Shruthe-96** [GENIVI/capicxx-core-tools#23]
Hello,

I am working on establishing inter-process communication between a CommonAPI Some/IP C++ server (Which uses FRANCA IDL and associated deployment files) and a Some/IP python client.

**Python Some/IP client**

Library used for python Some/IP client:

someip 0.1.0, Pysomeip (https://pypi.org/project/someip/ )

import someip.header

from someip.sd import SOMEIPDatagramProtocol

**Franca C++ Server**

The C++ server that is used was setup as per the following link:

https://at.projects.genivi.org/wiki/pages/viewpage.action?pageId=5472320

**Work done till now:**

(C++ vsomeip server) <-------------------------- > (python client)   **Result**: RPC Worked here.

Tried Some/IP IPC using a basic C++ vsomeip server (Which does not include CommonAPI and Franca) and the python client.

**Server C++**

Used the “Request/Response” example from the following link as the C++ server:

https://github.com/GENIVI/vsomeip/wiki/vsomeip-in-10-minutes

Snapshot 1 has log message on the Server Terminal Side.

**Client Python**

And the following example as the python client:

https://github.com/afflux/pysomeip/blob/master/tools/get.py

Snapshot 2 has the python side terminal log

I am attaching the snapshot of the IPC between the server and client:

Server:
![image](https://user-images.githubusercontent.com/67730368/86353193-8158b200-bc84-11ea-89d6-10a6a25c0dcb.png)
**Fig: Snapshot 1**

Client:
![image](https://user-images.githubusercontent.com/67730368/86353298-a9481580-bc84-11ea-9155-d69ca56a3355.png)
**Fig: Snapshot 2**

 **Issue Details:**

On using the same client code to establish communication with the C++server code (Containing franca and commonAPI as mentioned in https://at.projects.genivi.org/wiki/pages/viewpage.action?pageId=5472320) the C++ server returns back an error saying “Malformed Message” as shown in snapshot 3:

![image](https://user-images.githubusercontent.com/67730368/86353414-cda3f200-bc84-11ea-9ce6-9d60b7316f2d.png)
**Fig: Snapshot 3**

The server here uses a .fidl file while the client does not contain any franca file for binding.

Since the server used in this case requires CommonAPI is there a way to use commonAPI at the python side.

Also, Are there any code generators for python which would take .fidl files and generate python codes for the same which could then be used at the client end?

Any other suggestion as to what direction to proceed on would be very much appreciated.

Thanks in advance.

**Comment by Siddharthav1** [comment]
Hello shruthe,

please create this issue in Some/ip repo. It wil be more better


Regards,
Siddhartha V
