### ISSUE TITLE
Is it possible to add the .zip files as the previous release?

### ISSUE THREAD

**Issue by rlokanathan** [GENIVI/capicxx-core-tools#26]
Hi,

I have check out the latest code changes on both capicxx-core-tools and capicxx-someip-tools. Currently, with the v3.20, I am not able to compile the capicxx-core-tools. It shows some weird errors at the PropertyAccessor.java. I tried recompiling it in both Linux and Windows environment using maven, but until now, the issue is still there.

Could you please add the .zip generator files similar to the previous release? That will make our job easier to generate the stub and proxy codes. 

Looking forward hearing from you.

**Comment by robinchung** [comment]
@lutzbichler Hi,dude,please help us to fix this problem by offering your .zip package.

**Comment by lutzbichler** [comment]
Done with v3.2.0.1
