### ISSUE TITLE
using CommonAPI in multithreading scene

### ISSUE THREAD

**Issue by ReleaseBug** [GENIVI/capicxx-core-tools#3]
Hi，
I am a beginner of learning CommonAPI.

And i am working on an example FIDL:
HelloWorld FIDL:
method say {
in {
String name
}
out {
String message
}
}

I have some questions about this method.
void HelloWorldStubImpl::say(const std::shared_ptrCommonAPI::ClientId _client, std::string name, sayReply_t reply)

I want to use [say] method in a multithreading scene, There exist a working thread called BackGroundWorker.
When HelloWorldStubImpl::say() is called, HelloWorldStubImpl::say() will not [reply] imediately but just sent a message to BackGroundWorker.
BackGroundWorker will work on this message and do something.

Q1: Is [reply] thread safe? can i call [reply] in BackGroundWorker's thread when BackGroundWorker has done its job?

Q2: Is there a better solution in this scene?

You may save my time if you can answer my questions. Thx~

**Comment by GenivivSOMEIPmaintainer** [comment]
Q1: It is thread.safe. 
Q2: You can do it like that. It is apossible solution; if there is a better solution depends on your application.
