### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by ReleaseBug** [GENIVI/capicxx-core-tools#4]
hi , I have found a memory leak problem with **Async** method.
When called Async method in a loop , memory usage just keep growing.
But, sync method no problem.

is this  a known problem? Or can you figure out why?

############### Here is my running environment ###############
dbus-1.8.20
common-api-runtime/common-api-dbus-runtime:3.1.5
Linux kickseed 3.13.0-93-generic #140-Ubuntu SMP Mon Jul 18 21:21:05 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

###############  Here is my consumer code ###############
.........
int32_t count = 0;
void callback(const CommonAPI::CallStatus& status, const int32_t& num) 
{
std::cout << "getGpsNumAsync num = " << num << " Status:" << (int)status << " count:" << count++ <<std::endl;
}
while (true) 
{
	gpsInfoConsumer->getGpsNumAsync(callback);
	std::this_thread::sleep_for(std::chrono::milliseconds(1));//with out sleep_for 1 ms, core dumped !!!
}
.........

**Comment by GenivivSOMEIPmaintainer** [comment]
I have tried to reproduce this problem with current CommonAPI versions but could not find the problem anymore. Even removing the line std::this_thread::sleep_for(std::chrono::milliseconds(1)) in the code doesn't lead to a core dump anymore. Ticket will be closed.
