### ISSUE TITLE
Error _dbus _dbus_check_is_valid_signature function undefine

### ISSUE THREAD

**Issue by samlee820820** [GENIVI/capicxx-core-tools#7]
When I use d_**bus-1.12.0**_, after do patch -p1 < </path/to/CommonAPI-D-Bus/src/dbus-patches/patch-names>.patch.  _dbus_check_is_valid_signature has been patched into /dbus-1.12.0/dbus/dbus-message.c.when building HelloWorld Example, build system tells  _dbus_check_is_valid_signature undefined

**Comment by GenivivSOMEIPmaintainer** [comment]
This ticket should be a CommonAPI-D-Bus ticket because the patches are part of capicxx-dbus-runtime. But there is already another ticket for the patches (solved with version 3.1.12.7).
