### ISSUE TITLE
Upgrade to Franca 0.11

### ISSUE THREAD

**Issue by kthoms** [GENIVI/capicxx-core-tools#8]
The latest available release of Franca is 0.11. Version constraints have to be updated in MANIFEST.MF and some minor code changes are required.

**Comment by gunnarx** [comment]
I like it.  Hopefully the maintainer will also look at your PRs and merge (maybe on a separate branch?)
@kthoms and @kbirken - I have always heard that capicxx only supports Franca 0.10.  I can see some internal structures were renamed, but are those changes (https://github.com/GENIVI/capicxx-core-tools/pull/9 and https://github.com/GENIVI/capicxx-dbus-tools/pull/6) the only needed changes?  (Or are there some new features in 0.11 that are not yet supported?)

**Comment by GenivivSOMEIPmaintainer** [comment]
Updates of the Franca version require a major release of CommonAPI. That means that we need CommonAPI 4 for Franca update (in the meanwhile it is Franca 0.12.0). The Franca update must be also done for all code generators (also SOME/IP). Due to heavy changes in the deployment concept we needed some more time for implementation. CommonAPI 4 is planned mid of 2018.

**Comment by kbirken** [comment]
@GenivivSOMEIPmaintainer Although this PR is already closed, let me add a quick question: Will CommonAPI4 be based on the normal Franca 0.12.x release?

Background of the question: Currently there are ongoing discussions regarding the component model support for Franca (so called "Franca+"), but I would appreciate if CommonAPI4 is still based on "plain" Franca (i.e., [franca/franca](https://github.com/franca/franca) without any components extensions). There are many CommonAPI users who would like to continue with per-interface code generation.

**Comment by kbirken** [comment]
@gunnarx A response to your question: Indeed Franca 0.10, 0.11 and 0.12 introduced some new features, which will not be supported by the PR above and the one for capicxx-dbus-tools. However, they would be still valuable, as they allow to use the Franca IDL feature set of 0.9.1 with the bugfixes and usability extensions of the later Franca versions.

**Comment by GenivivSOMEIPmaintainer** [comment]
Of course we start with plain Franca 0.12.x for the code generators; we change the EA <-> Franca transformation first. If we introduce Franca+ to the code generators I think it should be no problem to integrate it as optional feature.
